filter:
    paths:
        - 'src/*'
    excluded_paths:
        - 'test/*'
before_commands:
    - 'composer install --prefer-source'
tools:
    php_mess_detector:
        filter:
            paths: ['src/*']
    php_cs_fixer:
        filter:
            paths: ['src/*']
    php_code_sniffer:
        filter:
            paths: ['src/*']
        config:
            standard: PSR1
    php_code_coverage:
        test_command: './acceptance_test.php && ./vendor/bin/phpunit'
        filter:
            paths: ['src/*']
        config_path: ./
    php_cpd:
        filter:
            paths: ['src/*']
    php_loc: true
    php_pdepend: true
